#Python Data Analysis with Pandas and Matplotlib: Create plots and manipulate data with Pandas and Matplotlib

This notebook is an adaptated version of the [10-Python-Data-Analysis-with-Pandas-and-Matplotlib.ipynb](https://colab.research.google.com/github/brainhack-uiowa/python-novice-inflammation-colab/blob/master/10_Python_Data_Analysis_with_Pandas_and_Matplotlib.ipynb) Google Colab Notebook.

In this workbook, we will learn the basics on analysis with Python and the Pandas library. we will also use the Matplot library for plotting this results.

#Tutorial aims:
1.   [Understand what Pandas is](https://pandas.pydata.org/docs/getting_started/overview.html)
2.   Ways of running Python and Pandas
3.   Understanding the basic Pandas data structures
4. Learn how to access data from a Pandas DataFrame
5. Learn how to filter data in a Pandas DataFrame
6.  Learn how to read and sort data from a file
7.  Understand the basics of the Matplotlib plotting package
8.   Learn how to bring together other packages to enhance your plots
9.    Learn how to further customise the appearance of Matplotlib plots
10.    Be inspired to experiment further with Matplotlib!

#1. What is Pandas?

`pandas` is a package commonly used to deal with data analysis. It simplifies the loading of data from external sources such as text files and databases, as well as providing ways of analysing and manipulating data once it is loaded into your computer. The features provided in `pandas` automate and simplify a lot of the common tasks that would take many lines of code to write in the basic Python langauge.

Pandas is best suited for structured, **labelled** data, in other words, tabular data, that has headings associated with each column of data. The [official Pandas website](https://pandas.pydata.org/) describes Pandas’ data-handling strengths as:
*   Tabular data with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet.
*   Ordered and unordered (not necessarily fixed-frequency) time series data.
* Arbitrary matrix data (homogeneously typed or heterogeneous) with row and column labels.
* Any other form of observational / statistical data sets. The data actually need not be labelled at all to be placed into a `pandas` data structure.

Some other important points to note about Pandas are:
* Pandas is **fast**. Python sometimes gets a bad rap for being a bit slow compared to ‘compiled’ languages such as C and Fortran. But deep down in the internals of Pandas, it is actually written in C, and so processing large datasets is no problem for Pandas.
* Pandas is a dependency of another library called `statsmodels`, making it an important part of the statistical computing ecosystem in Python.

You can read more about the Pandas package at the [Pandas project website](https://pandas.pydata.org/).

# 2. Working with Pandas

There are several conventions to follow when working with pandas,
- Use import `pandas` as `pd` to give a library a short alias while importing it.
- Then refer to items in the library using that shortened name.

##Conventions when using Pandas

All the examples in this tutorial assume you have installed the Python library `pandas`, either through installing a scientific Python distribution such as Anaconda, or by installing it using a package-manager, such as `conda` or `pip`. To use any of the features of Pandas, you will need to have an `import` statement at the top of your script like so:

In [ ]:
import pandas as pd

By convention, the `pandas` module is almost always imported this way as `pd`. Every time we use a `pandas` feature thereafter, we can shorten what we type by just typing `pd`, such as `pd.some_function()`.


Try the following to see which version of Pandas you are running:

In [ ]:
import pandas as pd

print(pd.__version__)

2.2.2

Run the code and note the output.

# 3. Understand the basic Pandas data structures

Pandas has two core data structures used to store data: The *Series* and the *DataFrame*.

##Series

The series is a one-dimensional array-like structure ([remember numpy?](https://numpy.org/doc/stable/user/quickstart.html)) designed to hold a single array (or ‘column’) of data and an associated array of data labels, called an *index*. We can create a series to experiment with by simply passing a list of data, let’s use numbers in this example:

In [ ]:
import pandas as pd

my_series = pd.Series([4.6, 2.1, -4.0, 3.0]) # create a series
print(my_series)

0    4.6
1    2.1
2   -4.0
3    3.0
dtype: float64

Note that printing out our Series object prints out the values and the index numbers. If we just wanted the values, we can add to our script the following line:

In [ ]:
print(my_series.values)

[ 4.6  2.1 -4.   3. ]

For a lot of applications, a plain old *Series* is probably not a lot of use, but it is the core component of the Pandas workhorse, the *DataFrame*, so it’s useful to know about.

##DataFrames

The DataFrame represents tabular data, a bit like a spreadsheet. DataFrames are organised into colums (each of which is a *Series*), and each column can store a single data-type, such as floating point numbers, strings, boolean values etc. DataFrames can be indexed by either their row or column names. (They are similar in many ways to R’s `data.frame`.)

We can create a DataFrame in Pandas from a Python dictionary, or by loading in a text file containing tabular data. First we are going to look at how to create one from a dictionary.

##A refresher on the Dictionary data type

Dictionaries are a core Python data structure that contain a set of `key:value` pairs. If you imagine having a written language dictionary, say for English-Spanish, and you wanted to know the Hungarian word for “spaceship”, you would look-up the English word (the dictionary `key` in Python) and the dictionary would give you the Hungarian translation (the dictionary `value` in Python). So the “key-value pair” would be `'spaceship': 'nave espacial'`.

To construct a dictionary in Python, the syntax we would write is:

In [ ]:
# Note that dictionaries are part of the core Python language
# You do not need 'import pandas' if you are only working with dictionaries.

spanigh_dictionary = {'spaceship': 'nave espacial'}

We could then look-up items in our dictionary with this syntax:

In [ ]:
spanigh_dictionary['spaceship']

'nave espacial'

Dictionaries can have multiple entries (multiple key-value pairs), and these are separated with a comma:

In [ ]:
spanigh_dictionary = {'spaceship': 'nave espacial',
                        'watermelon': 'melón',
                        'bicycle': 'bicicleta'}

The `values` in dictionaries are not limited to single strings or words. Values can be any Python object such as numbers, lists, tuples, or even other dictionaries:

In [ ]:
# Sample numbers (keys) mapped to a tuple (the value) containing abundance in different bacteria: 'Bacteroides vulgatus',	'Bacteroides uniformis',	'Bacteroides thetaiotaomicron', 'Faecalibacterium prausnitzii',	'Roseburia faecis'
hospital_samples = {'Carlos': (1345, 56.79685, 5.003508),
            'Giulia': (1309, 57.070453, 3.668262),
            'Felipe': (1296, 57.078628, 3.728024),
            'Gustavo': (1291, 57.054611, 3.71042),
            'Karla': (1258, 57.057999, 3.725416)}

Looking up a Bacterium using its name as the key would then give us the reltive abundance in three samples

In [ ]:
hospital_samples['Carlos']

(1345, 56.79685, 5.003508)

##Back to DataFrames…

If we didn’t have any real data to play with from an external file, we could manually create a DataFrame from a Python dictionary. Using the `hospital_samples` dictionary above, we can load it into a Pandas DataFrame with this syntax:
```
dataframe = pd.DataFrame(hospital_samples)
```

**Note**: You will sometimes see `df` used as shorthand convention for a `DataFrame` object in many Pandas examples.

Try creating a Python script that converts a Python dictionary into a Pandas DataFrame, then print the DataFrame to screen. You can use the `hospital_samples` example or experiment with your own.

In [ ]:
hospital_samples = {'Carlos': (1345, 56.79685, 5.003508),
            'Giulia': (1309, 57.070453, 3.668262),
            'Felipe': (1296, 57.078628, 3.728024),
            'Gustavo': (1291, 57.054611, 3.71042),
            'Karla': (1258, 57.057999, 3.725416)}


dataframe = pd.DataFrame(hospital_samples)
print(dataframe)

        Carlos       Giulia       Felipe      Gustavo        Karla
0  1345.000000  1309.000000  1296.000000  1291.000000  1258.000000
1    56.796850    57.070453    57.078628    57.054611    57.057999
2     5.003508     3.668262     3.728024     3.710420     3.725416

Now, this is not necessarily the most logical order to store data. It would probably make more sense for the columns to be categories or types of data, rather than the names of each hill. You may remember from previous workshops that the data is currently in `wide` format, but we want it in `long` format. To do this, we need to think about how to structure our dictionary. Pandas works best with dictionaries when the dictionary keys refer to column names or headers. Here’s a better dictionary to use:

In [ ]:
hospital_samples = {'Patient Name': ['Carlos', 'Giulia',	'Felipe', 'Gustavo', 'Karla'],
                  'Bacteroides thetaiotaomicron': [1345, 1309, 1296, 1291, 1258],
                  'Faecalibacterium prausnitzii': [56.79685, 57.070453, 57.078628, 57.054611, 57.057999],
                  'Roseburia faecis': [20.0, 30.668262, 372, 32, 78.76]}

We’ve made the dictionary keys into category-like names, and then these are followed by a list of corresponding data values. Pandas will be able to read this better. Replace the dictionary in your script above and run it again. Now you should get the following output:

In [ ]:
hospital_samples

{'Patient Name': ['Carlos', 'Giulia', 'Felipe', 'Gustavo', 'Karla'],
 'Bacteroides thetaiotaomicron': [1345, 1309, 1296, 1291, 1258],
 'Faecalibacterium prausnitzii': [56.79685,
  57.070453,
  57.078628,
  57.054611,
  57.057999],
 'Roseburia faecis': [20.0, 30.668262, 372, 32, 78.76]}

This is a more useful layout for our DataFrame. The column names are ordered alphabetically by default (left to right), but we can specify the order using the `columns` keyword. (Another way would be to use an `OrderedDict` data structure, but that’s not covered in this tutorial…)

In your original script, replace the line where you create the DataFrame with the following:

In [ ]:
dataframe = pd.DataFrame(hospital_samples)

Run the modified script. You should now get output that looks like this:

In [ ]:
dataframe

,Patient Name,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis
0,Carlos,1345,56.796850,20.000000
1,Giulia,1309,57.070453,30.668262
2,Felipe,1296,57.078628,372.000000
3,Gustavo,1291,57.054611,32.000000
4,Karla,1258,57.057999,78.760000

Note how the dictionary keys have become column headers running along the top, and as with the Series, an index number has been automatically generated.

#4. Learn how to access data from a Pandas DataFrame (Review)

Pandas DataFrames have many useful methods that can be used to inspect the data and manipulate it. We are going to have a look at just a few of them.

If our DataFrame was huge, we would not want to print all of it to screen, instead we could have a look at the first `n` items with the `head` method, which takes the number of rows you want to view as its argument. If we added this to the end of our script and ran it again, it would print:

In [ ]:
dataframe.head(3)

,Patient Name,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis
0,Carlos,1345,56.796850,20.000000
1,Giulia,1309,57.070453,30.668262
2,Felipe,1296,57.078628,372.000000

We could also look at the last `n` rows with the `tail` method, which would give us:

In [ ]:
dataframe.tail(2)

,Patient Name,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis
3,Gustavo,1291,57.054611,32.00
4,Karla,1258,57.057999,78.76

Our columns in the `dataframe` object are individual Series of data. We can access them by referring to the column name e.g. `dataframe['column-name']`. Have a go at adding these extra statements to your script, and check that you get the same output:

In [ ]:
dataframe['Patient Name']

0     Carlos
1     Giulia
2     Felipe
3    Gustavo
4      Karla
Name: Patient Name, dtype: object

And:

In [ ]:
dataframe['Bacteroides thetaiotaomicron']

0    1345
1    1309
2    1296
3    1291
4    1258
Name: Bacteroides thetaiotaomicron, dtype: int64

Note that Pandas DataFrames are accessed *primarily by columns*. In a sense the row is less important to a DataFrame. For example, what do you think would happen using the following code?

In [ ]:
dataframe[0]

KeyError: 0

Ouch! That’s a lot of error messages… **The columns cannot be accessed by their index number in this way**, you must use the column name. You may have thought that this might return the row index instead, but we have to use a different method to get the row:

In [ ]:
dataframe.iloc[0]

Patient Name                      Carlos
Bacteroides thetaiotaomicron        1345
Faecalibacterium prausnitzii    56.79685
Roseburia faecis                    20.0
Name: 0, dtype: object

The `iloc` method gives us access to the DataFrame in more traditional ‘matrix’ style notation, i.e. `[row, column]` notation. So if we wanted to get the abundance of Bacterioides vulgatus in Sample1, we could do:

In [ ]:
dataframe.iloc[0,0]

'Carlos'

A way to remeber this is that `iloc` is short for “integer location”. But if we cannot count on the 0th column always being "Hill Name", we can explicitly
reference the "Hill Name" column using the `.loc` method.

In [ ]:
dataframe.loc[0, 'Patient Name']

'Carlos'

#5. Learn how to filter data in a Pandas DataFrame

We can also apply conditions to the data we are inspecting, such as to filter our data.

In [ ]:
dataframe["Roseburia faecis"] > 50

0    False
1    False
2     True
3    False
4     True
Name: Roseburia faecis, dtype: bool

This returns a new Series of True/False values though. To actually filter the data, we need to use this Series to mask our original DataFrame:

In [ ]:
dataframe[dataframe["Roseburia faecis"] > 50]

,Patient Name,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis
2,Felipe,1296,57.078628,372.00
4,Karla,1258,57.057999,78.76

##Learn how to append data to an existing DataFrame

We can also append data to the DataFrame. This is done using the following syntax:

In [ ]:
dataframe['diagnosis'] = ['healthy', 'cd', 'uc', 'cd', 'uc']

In [ ]:
dataframe.head()

,Patient Name,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis,diagnosis
0,Carlos,1345,56.796850,20.000000,healthy
1,Giulia,1309,57.070453,30.668262,cd
2,Felipe,1296,57.078628,372.000000,uc
3,Gustavo,1291,57.054611,32.000000,cd
4,Karla,1258,57.057999,78.760000,uc

In [ ]:
# Count number of columns
print(dataframe.shape[1]) # option 1
print(len(dataframe.columns)) # option 2
print(dataframe.columns)

5
5
Index(['Patient Name', 'Bacteroides thetaiotaomicron',
       'Faecalibacterium prausnitzii', 'Roseburia faecis', 'diagnosis'],
      dtype='object')

In [ ]:
# Count number of different patients

dataframe['Patient Name'].nunique()

5

In [ ]:
# Count the number of patients with each fiagnosis
dataframe['diagnosis'].value_counts()

diagnosis
cd         2
uc         2
healthy    1
Name: count, dtype: int64

## Statistical Functions in Pandas

Let's explore some basic statistical functions provided by Pandas to get a quick overview of our DataFrame's numerical data.

### `describe()`: Generate descriptive statistics

### `sum()`: Calculate the sum of each column

In [ ]:
print("Sum of each numerical column:")
display(dataframe.select_dtypes(include=['number']).sum()) # select only the columns that have a numeric data type (e.g., integers or floats) and calculate the sum

Sum of each numerical column:

Bacteroides thetaiotaomicron    6499.000000
Faecalibacterium prausnitzii     285.058541
Roseburia faecis                 533.428262
dtype: float64

### `mean()`: Calculate the mean of each numerical column

In [ ]:
print("Mean of each numerical column:")
display(dataframe.select_dtypes(include=['number']).mean())

Mean of each numerical column:

Bacteroides thetaiotaomicron    1299.800000
Faecalibacterium prausnitzii      57.011708
Roseburia faecis                 106.685652
dtype: float64

### `min()` and `max()`: Find the minimum and maximum values in numerical columns

In [ ]:
print("Minimum values in numerical columns:")
display(dataframe.select_dtypes(include=['number']).min())

print("\nMaximum values in numerical columns:")
display(dataframe.select_dtypes(include=['number']).max()) # try include='all'

Minimum values in numerical columns:

Bacteroides thetaiotaomicron    1258.00000
Faecalibacterium prausnitzii      56.79685
Roseburia faecis                  20.00000
dtype: float64

Maximum values in numerical columns:

Bacteroides thetaiotaomicron    1345.000000
Faecalibacterium prausnitzii      57.078628
Roseburia faecis                 372.000000
dtype: float64

### `count()`: Count non-null values for each column

In [ ]:
print("Count of non-null values for each column:")
display(dataframe.count())

Count of non-null values for each column:

Patient Name                    5
Bacteroides thetaiotaomicron    5
Faecalibacterium prausnitzii    5
Roseburia faecis                5
dtype: int64

#6. Learn how to read data from a file using Pandas

So far we have only created data in Python itself, but Pandas has built in tools for reading data from a variety of external data formats, including Excel spreadsheets, raw text and `.csv` files. It can also interface with databases such as MySQL, but we are not going to cover databases in this tutorial.

We will be using HMP2 IBD data downloaded frmo Keggel.

In [ ]:
# Option 1: load directly from github

# Point to the 'raw' version of the file. We use raw.githubusercontent.com. It is a special domain used by GitHub to serve pure, unformatted files directly to computers and applications.
file_path = 'https://raw.githubusercontent.com/hector-ahg/predictive-microbiology-course/main/dataset/other_hmp2_dataset_kaggel/hmp2_ibd_metagenomics_atlas_20260219_121629.csv'

# Loading the data
df = pd.read_csv(file_path)

# Verification
df.head()

In [75]:
# Option 2: clone Github Repo in Colab and fetch datafile from there (recommended when you need to follow the folder structure)

import pandas as pd

# Clone GitHub repo to Colab
REPO_URL = "https://github.com/hector-ahg/predictive-microbiology-course.git"

!git clone $REPO_URL # You should see a "predictive-microbiology-course" folder in your colab Files (folder icon on the left bar)
%cd predictive-microbiology-course
!ls

file_path= "./dataset/other_hmp2_dataset_kaggel/hmp2_ibd_metagenomics_atlas_20260219_121629.csv"
df = pd.read_csv(file_path) # read the file in the file_path

Cloning into 'predictive-microbiology-course'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 127 (delta 18), reused 21 (delta 5), pack-reused 86 (from 1)
Receiving objects: 100% (127/127), 66.00 MiB | 33.64 MiB/s, done.
Resolving deltas: 100% (21/21), done.
/content/predictive-microbiology-course/predictive-microbiology-course/predictive-microbiology-course/predictive-microbiology-course
data_links.md  docs	notebooks  raw_results	requirements.txt
dataset        figures	pipeline   README.md

In [76]:
# Check df dimensions
df.shape # we have 3387 rows (External IDs or samples) and 571 columns (bacteria)

(3387, 571)

In [80]:
df.columns

Index(['External ID', 'Participant ID', 'week_num', 'diagnosis', 'fecalcal',
       'Bacteroides vulgatus', 'Bacteroides uniformis',
       'Bacteroides thetaiotaomicron', 'Faecalibacterium prausnitzii',
       'Roseburia faecis',
       ...
       'Prevotella histicola', 'Prevotella pallens', 'Chlamydia ibidis',
       'Enterococcus mundtii', 'Anaerostipes sp 992a',
       'Actinobaculum sp oral taxon 183', 'Lachnoclostridium sp An298',
       'Haemophilus haemolyticus', 'Enterococcus dispar', 'Atopobium minutum'],
      dtype='object', length=571)

In [83]:
# We can make a subset only with data from patients with Ulcerative Colitis

df_UC = df[df['diagnosis']=='Ulcerative Colitis']
df_UC.head()

,External ID,Participant ID,week_num,diagnosis,fecalcal,Bacteroides vulgatus,Bacteroides uniformis,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis,...,Prevotella histicola,Prevotella pallens,Chlamydia ibidis,Enterococcus mundtii,Anaerostipes sp 992a,Actinobaculum sp oral taxon 183,Lachnoclostridium sp An298,Haemophilus haemolyticus,Enterococcus dispar,Atopobium minutum
10,CSM5FZ4K,C3003,7.0,Ulcerative Colitis,5.5400,0.00504,25.66730,0.99493,9.92632,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,CSM67UBZ,C3003,26.0,Ulcerative Colitis,12.7000,0.00000,20.69142,1.40046,9.08473,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,CSM79HLM,C3003,38.0,Ulcerative Colitis,14.3000,0.00000,26.94663,0.59322,2.41174,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,CSM5FZ4A,C3004,0.0,Ulcerative Colitis,9.5400,26.47248,27.85890,0.00123,0.65194,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,CSM5MCXL,C3004,16.0,Ulcerative Colitis,14.8241,28.66024,17.40725,0.00000,1.24878,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

We’ve used the `head()` function to give us only the first 5 items in the DataFrame, and avoid printing all 3387 samples out to screen…

It looks like this table contains the hills in alphabetical order. It would be nice to see them in order of height. We can sort the DataFrame using the `sort_values` method. You can add the following lines to your script:

In [77]:
sorted_df = df.sort_values(by=['Bacteroides vulgatus'], ascending=False)

# Let's have a look at the top 5 to check
sorted_df.head(5)

,External ID,Participant ID,week_num,diagnosis,fecalcal,Bacteroides vulgatus,Bacteroides uniformis,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis,...,Prevotella histicola,Prevotella pallens,Chlamydia ibidis,Enterococcus mundtii,Anaerostipes sp 992a,Actinobaculum sp oral taxon 183,Lachnoclostridium sp An298,Haemophilus haemolyticus,Enterococcus dispar,Atopobium minutum
2929,HSM6XRSG,H4004,24.0,Crohns Disease,47.07077,93.61109,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
768,HSM6XRSG,H4004,24.0,Crohns Disease,47.07077,93.61109,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1825,HSM6XRSG,H4004,24.0,Crohns Disease,47.07077,93.61109,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
131,HSM6XRSG,H4004,24.0,Crohns Disease,47.07077,93.61109,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2417,HSM6XRSG,H4004,24.0,Crohns Disease,47.07077,93.61109,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

We now have our hills sorted by the value of 'Bacteroides vulgatus'. Note how we’ve used the `by=['Bacteroides vulgatus']` argument to specify that we want to sort by Bacteroides vulgatus, and then the `ascending=False` argument to get the heights sorted in descending order, from highest to lowest.

In [70]:
# you may want to remove columns

df_without_week_num = df.copy() # we first copy the df since this will modify the original df loaded in memory
df_without_week_num = df_without_week_num.drop(columns=['week_num', 'fecalcal'])
df_cols = df_without_week_num.columns

if 'week_num' and 'fecalcal' in df_cols:
    print("The 'week_num' and 'fecalcal' columns are still in the DataFrame.")
else:
    print("The 'week_num' and 'fecalcal' columns have been removed.")

The 'week_num' and 'fecalcal' columns have been removed.

As you can see above, printing `grouped_df` directly gives you information about the object itself, not the aggregated data. To get a summary *from* the grouped object, you need to apply an aggregation method, like `.size()` to count items in each group:

In [71]:
# Example: Count the number of entries in each 'diagnosis' group
grouped_size = df_without_week_num.groupby('diagnosis').size()
display(grouped_size)
print("Number of healthy patients:", int(grouped_size['Healthy']))

diagnosis
Crohns Disease        1608
Healthy                866
Ulcerative Colitis     913
dtype: int64

Number of healthy patients: 866

We can also perform statistics for each group

In [72]:
# group df by certain charateristic and perfomr a statistical function

grouped_means = df_without_week_num.groupby('diagnosis').mean(numeric_only=True)
grouped_means

,Bacteroides vulgatus,Bacteroides uniformis,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis,Bacteroides caccae,Clostridium clostridioforme,Bacteroides fragilis,Fusicatenibacter saccharivorans,Flavonifractor plautii,...,Prevotella histicola,Prevotella pallens,Chlamydia ibidis,Enterococcus mundtii,Anaerostipes sp 992a,Actinobaculum sp oral taxon 183,Lachnoclostridium sp An298,Haemophilus haemolyticus,Enterococcus dispar,Atopobium minutum
diagnosis,,,,,,,,,,,,,,,,,,,,,
Crohns Disease,17.336165,10.667527,1.874664,7.230407,1.747169,2.314792,0.244706,3.660239,0.449797,0.958050,...,0.000000,0.000000,0.24908,0.003262,0.000000,0.000000,0.000000,0.000116,0.000005,0.000000
Healthy,13.678290,7.994443,1.713188,9.627604,3.047973,2.532310,0.081663,1.058683,0.298401,0.518344,...,0.000000,0.000000,0.00000,0.000000,0.003275,0.000303,0.000018,0.000000,0.000000,0.000000
Ulcerative Colitis,18.411697,9.766831,1.701736,9.501842,2.705741,2.191602,0.006090,2.993326,0.393059,0.708046,...,0.000299,0.000106,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000066

In [73]:
# ¿Para qué sirve idxmax(axis=0)?

grouped_means.idxmax(axis=0)

Bacteroides vulgatus               Ulcerative Colitis
Bacteroides uniformis                  Crohns Disease
Bacteroides thetaiotaomicron           Crohns Disease
Faecalibacterium prausnitzii                  Healthy
Roseburia faecis                              Healthy
                                          ...
Actinobaculum sp oral taxon 183               Healthy
Lachnoclostridium sp An298                    Healthy
Haemophilus haemolyticus               Crohns Disease
Enterococcus dispar                    Crohns Disease
Atopobium minutum                  Ulcerative Colitis
Length: 566, dtype: object

In [74]:
# what about idxmax(axis=1)?

grouped_means.idxmax(axis=1)

diagnosis
Crohns Disease        Bacteroides vulgatus
Healthy               Bacteroides vulgatus
Ulcerative Colitis    Bacteroides vulgatus
dtype: object

# Exercises

Your turn! Solve the following exercises.

Question 0: How many DIFFERENT "Participant ID" are in the df DataFrame?

In [5]:
# Type your answer
df['Participant ID'].nunique()

116

Question 1: What are the main statistical properties (mean, std, min, max, quartiles) for all numerical columns in the df DataFrame?

In [85]:
# Type your answer

df.describe()

,week_num,fecalcal,Bacteroides vulgatus,Bacteroides uniformis,Bacteroides thetaiotaomicron,Faecalibacterium prausnitzii,Roseburia faecis,Bacteroides caccae,Clostridium clostridioforme,Bacteroides fragilis,...,Prevotella histicola,Prevotella pallens,Chlamydia ibidis,Enterococcus mundtii,Anaerostipes sp 992a,Actinobaculum sp oral taxon 183,Lachnoclostridium sp An298,Haemophilus haemolyticus,Enterococcus dispar,Atopobium minutum
count,3387.000000,1360.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,...,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000,3387.000000
mean,21.125185,112.464996,16.690827,9.741272,1.786763,8.455619,2.338156,2.337201,0.138697,2.815291,...,0.000081,0.000028,0.118252,0.001549,0.000837,0.000078,0.000005,0.000055,0.000002,0.000018
std,13.921611,119.385625,17.595044,11.038892,3.586893,10.139353,5.676540,3.705806,0.871576,7.667186,...,0.004692,0.001656,3.435026,0.045042,0.014656,0.003065,0.000190,0.003211,0.000081,0.000521
min,0.000000,3.620000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,16.000000,0.038580,0.528210,0.000000,1.496000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,20.000000,44.012000,11.783010,6.367390,0.274600,5.075400,0.154020,0.927190,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,34.000000,211.241975,28.094040,14.629320,1.900490,11.235830,1.910710,3.381630,0.000000,1.555000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,57.000000,493.700000,93.611090,87.792870,35.199170,71.301700,60.810610,46.076430,24.457480,82.348180,...,0.273070,0.096400,100.000000,1.311270,0.324850,0.125910,0.007840,0.186870,0.002720,0.015170

Question 2: How many patients are diagnosed with "Crohns  Disease" and "Ulcerative Colitis"?

In [47]:
# Type your answer
grouped_size = df_without_week_num.groupby('diagnosis').size()
print("Patients are diagnosed with Crohns Disease and Ulcerative Colitis:", int(grouped_size['Crohns Disease']) + int(grouped_size['Ulcerative Colitis']))

Patients are diagnosed with Crohns Disease and Ulcerative Colitis: 2521

Question 3: What is the most abundant taxa for each group at week 24?

In [99]:
df_week24 = df[df['week_num'] == 24]

# group by participant and compute mean abundance
df_week24_grouped = (
    df_week24
    .drop(columns=['week_num', 'diagnosis'])
    .groupby('Participant ID')
    .mean(numeric_only=True)
)

# most abundant taxa for each participant
most_abundant_taxa = df_week24_grouped.idxmax(axis=1)

display(most_abundant_taxa)

Participant ID
C3001              Bacteroides caccae
C3002            Bacteroides vulgatus
C3004            Bacteroides vulgatus
C3005               Bacteroides dorei
C3008               Bacteroides dorei
C3011            Coprococcus eutactus
C3012           Bacteroides uniformis
C3013                Prevotella copri
C3015           Bacteroides uniformis
C3016                        fecalcal
C3017            Bacteroides vulgatus
C3021           Bacteroides uniformis
C3023               Prevotella sp 885
C3028            Bacteroides vulgatus
C3031           Bacteroides uniformis
C3032           Bacteroides uniformis
C3035           Bacteroides stercoris
E5001            Bacteroides vulgatus
E5004            Bacteroides vulgatus
H4004            Bacteroides vulgatus
H4006            Bacteroides fragilis
H4007            Bacteroides vulgatus
H4008            Bacteroides vulgatus
H4013           Bacteroides stercoris
H4016            Bacteroides vulgatus
H4018           Bacteroides stercoris
H4019    Faecalibacterium prausnitzii
H4020      Parabacteroides distasonis
H4023                        fecalcal
H4024                        fecalcal
H4027            Bacteroides vulgatus
H4030           Bacteroides stercoris
H4031            Bacteroides vulgatus
H4035            Bacteroides vulgatus
H4038            Bacteroides vulgatus
H4039          Roseburia intestinalis
H4044            Bacteroides vulgatus
M2014                        fecalcal
M2025           Bacteroides uniformis
M2026            Bacteroides vulgatus
M2027                Prevotella copri
M2028            Bacteroides vulgatus
M2039    Faecalibacterium prausnitzii
M2041            Bacteroides vulgatus
M2069    Faecalibacterium prausnitzii
M2072               Bacteroides dorei
M2075    Faecalibacterium prausnitzii
M2077            Bacteroides vulgatus
M2097               Bacteroides dorei
M2103                        fecalcal
P6005            Bacteroides vulgatus
P6016           Bacteroides uniformis
P6018    Faecalibacterium prausnitzii
P6033           Bacteroides uniformis
P6037               Bacteroides dorei
P6038           Bacteroides uniformis
dtype: object

#7. Understand the basics of the Matplotlib plotting package (Review)

`matplotlib` is a Python package used for data plotting and visualisation. It is a useful complement to Pandas, and like Pandas, is a very feature-rich library which can produce a large variety of plots, charts, maps, and other visualisations. It would be impossible to cover the entirety of Matplotlib in one tutorial, so this section is really to give you a flavour of the capabilities of Matplotlib, and to cover some of the basics, as well as a couple of more interesting ‘advanced’ features.

If you have a bit of basic Python knowledge already, the common route to learning Matplotib is to find examples of plots similar to ones you are trying to create and walk through them, trying to reproduce them with your own data perhaps. A great starting point is the [Matplotlib gallery of examples](https://matplotlib.org/gallery.html). I recommend this because in practice it is difficult to cover each and every plot type, as the needs of scientists differ considerably depending on the type of data they are working with or the message they are trying to convey in their visualisation. You might also find it useful to refer to the [Matplotlib official documentation](https://matplotlib.org/api/pyplot_api.html) as you go along.


##Matplotlib conventions

Like Pandas, Matplotlib has a few conventions that you will see in the examples, and in resources on other websites such as StackOverflow. Typically, if we are going to work on some plotting, we would import `matplotlib` like this:

In [ ]:
import matplotlib.pyplot as plt

And thereafter, we could access the most commonly used features of Matplotlib with `plt` as shorthand. Note that this `import` statement is at the *submodule* level. We are not importing the full `matplotlib` module, but a subset of it called `pyplot`. Pyplot contains the most useful features of Matplotlib with an interface that makes interactive-style plotting easier. Submodule imports have the form `import module.submodule` and you will see them used in other Python libraries too sometimes.

##Matplotlib basics

We’re going to use the HMP2 IBD data from the Pandas section of the tutorial, so if you need to set this up again, the script should look like this to begin with:

Let’s have a look at the relationship between two varibles in our Scottish hills data. Suppose I have a hypothesis that the height of Scottish hill increases with latitude northwards. Were going to plot height against latitude. To save typing later on, we can extract the Series for “Height” and “Latitude” by assigning each to a new variable, `x` and `y`, respectively.

(This saves us having to type `dataframe.Height` etc. every time)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

file_path = 'https://raw.githubusercontent.com/hector-ahg/predictive-microbiology-course/main/dataset/other_hmp2_dataset_kaggel/hmp2_ibd_metagenomics_atlas_20260219_121629.csv'

# Loading the data
df = pd.read_csv(file_path)

# Verification
df.head()

taxa1 = df["Bacteroides uniformis"]
taxa2 = df["Intestinimonas butyriciproducens"]

# pythonic style (preferred)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.scatter(taxa1, taxa2)

In [ ]:
# matlab style (not preferred)
plt.scatter(x, y)

In [ ]:
from numpy import log10

# 1. Prepare the data (using descriptive variable names)
taxa_x1 = log10(df["Bacteroides uniformis"])
taxa_y1 = log10(df["Intestinimonas butyriciproducens"])
taxa_x2 = log10(df["Anaerotignum lactatifermentans"])
taxa_y2 = log10(df["Dialister invisus"])

# 2. Setup the figure (Object-Oriented Style)
# We define a 1x2 grid (1 row, 2 columns)
fig = plt.figure(figsize=(12, 5))

# 3. First Plot (Left side)
# (rows, cols, index) -> 1 row, 2 columns, 1st position
ax1 = fig.add_subplot(1, 2, 1)
ax1.scatter(taxa_x1, taxa_y1, alpha=0.5, color='blue')
ax1.set_title("B. uniformis vs I. butyriciproducens")
ax1.set_xlabel("log10 Abundance")
ax1.set_ylabel("log10 Abundance")

# 4. Second Plot (Right side)
# (rows, cols, index) -> 1 row, 2 columns, 2nd position
ax2 = fig.add_subplot(1, 2, 2)
ax2.scatter(taxa_x2, taxa_y2, alpha=0.5, color='green')
ax2.set_title("A. lactatifermentans vs D. invisus")
ax2.set_xlabel("log10 Abundance")

# Adjust layout so titles don't overlap
plt.tight_layout()
plt.show()

We demonstrated two styles of plotting with matplotlib: "pythonic" and "matlab".
While the pythonic style is more verbose (i.e., more lines of code), it gives you more control over your plotting in case you needed to add another subplot (axis) to your figure. The matlab style does not have a straightforward method to create and modify several subplots (axes).

The matlab style was created back in 2003 when matlab was still the dominant programming language.

#8. Learn how to bring together other Python libraries with Matplotlib

Now we are going to do some basic statistics so we can plot a line of linear regression on our chart.

Let’s plot a linear regression through the data. Python has a library called `scipy` that contains a lot of statistics routines. We can import it by adding to the top of our script:

In [ ]:
from scipy.stats import linregress

Then at the bottom of our script, we are going to get statistics for the linear regression by using a function called `linregress` by adding the following line. Don’t worry, we will go through below how all of this works. These are the lines you need to add to the end of your script:

In [ ]:
stats = linregress(taxa1, taxa2)

m = stats.slope
b = stats.intercept

Let’s pause and recap what we’ve done here before plotting the regression.

1.    We used an `import` statement with a slightly different format here: `from module.submodule import function`. This is a handy way of importing just a single function from a Python module. In this case we only want to use the `linregress` function in SciPy’s `stats` submodule, so we can just import it without anything else using that syntax.
2.    Next we are assigning the results of `linregress` to variable called `stats`.
3.    The `linregress` function is slightly different to the functions we’ve seen so far, because it returns an object with multiple values. In fact it returns the `slope`, `intercept`, `rvalue`, `pvalue`, and `stderr` (standard error). We can get hold of each of these values by using the dot notation: e.g. `stats.slope`, for example, much in the same way we can access our DataFrame attributes with `dataframe.Height`.
4.    For ease of typing later, we’ve assigned the `stats.slope` to a variable `m`, and `stats.intercept` to a variable `b`.

The equation for the straight line that describes linear regression is `y = mx + b`, where `m` is the slope and `b` is the intercept.

Therefore, we can then plot the line of linear regression by adding the following line:

In [ ]:
# pythonic style (preferred)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(taxa1, m * taxa1 + b, color='red', label="Trendline") # The equation of the straight line.

In [ ]:
# matlab style
plt.plot(taxa1, m * taxa1 + b)  # The equation of the straight line.

That’s a lot of new Python, so let’s review what the final script should look like:

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress
import numpy as np


file_path = 'https://raw.githubusercontent.com/hector-ahg/predictive-microbiology-course/main/dataset/other_hmp2_dataset_kaggel/hmp2_ibd_metagenomics_atlas_20260219_121629.csv'

# Loading the data
df = pd.read_csv(file_path)

x_log = np.log10(df['Intestinimonas butyriciproducens'] + 1e-6)
y_log = np.log10(df['Ruminococcus bicirculans'] + 1e-6)

# 2. Perform regression on the cleaned data
stats = linregress(x_log, y_log)

# 3. Plotting
fig, ax = plt.subplots()
ax.scatter(x_log, y_log, alpha=0.3)

# Now the line will appear because m and b are real numbers!
ax.plot(x_log, stats.slope * x_log + stats.intercept, color="red")

ax.set_xlabel("log10 Abundance (Species A)")
ax.set_ylabel("log10 Abundance (Species B)")

The issue is that we have a lot of values close to zero. We can remove them and see what happen

#9. Learn how to customise Matplotlib plots further

Matplotlib figures are highly customisable, and there are so many options it is usually best to consult the [documentation first](https://matplotlib.org/tutorials/index.html). In addition, the [Matplotlib official pyplot tutorial is quite useful](https://matplotlib.org/users/pyplot_tutorial.html). To get started on Matplotlib plot customisation, here is an extended version of the above which sets the font sizes, axes lables, linewidths, and marker types:

Again, the best way to learn the features of Matplotlib is by example, so try to modify your script above with some of the extra arguments added below, such as `fontsize`, `linewidth`, `color`, etc. Have a go at adding your own values, and producing nicer looking plots. Here’s my example to start you off:

In [ ]:
# Create a filter: Keep only rows where BOTH species are > 0
mask = (df['Intestinimonas butyriciproducens'] > 0) & (df['Ruminococcus bicirculans'] > 0)

# Apply the filter to create a "clean" subset
filtered_df = df[mask].copy()

# Now take the log (no pseudocount needed!)
x_log = np.log10(filtered_df['Intestinimonas butyriciproducens'])
y_log = np.log10(filtered_df['Ruminococcus bicirculans'])

# 4. Perform regression
stats = linregress(x_log, y_log)

# 5. Plotting
fig, ax = plt.subplots(figsize=(8, 6))
ax.scatter(x_log, y_log, alpha=0.5, edgecolors='w')
ax.plot(x_log, stats.slope * x_log + stats.intercept, color="red", label=f"R² = {stats.rvalue**2:.3f}")

ax.set_title("Correlation (Non-zero abundance only)", fontsize= 18)
ax.set_xlabel("log10 Abundance (Species A)", fontsize= 14)
ax.tick_params(axis='both', labelsize=14)
ax.set_ylabel("log10 Abundance (Species B)", fontsize= 14)
ax.legend()
plt.show()

# Exercise
Make a barplot of the number of patients with Crohns Desease, Healty and Ulvertive Colitis

In [ ]:
# Your code

#Summary

In this tutorial we have covered the various ways in which we can use Pandas, Matplotlib, and a few other Python libraries to start doing data analysis.

#Tutorial outcomes

1.    Understood what the Pandas library does
2.    Understood the basic Pandas data structures and how to manipulate them.
3.    Understood the basics of the Matplotlib plotting package
4.    Learnt how to bring use additional packages to enhance your plots